#!/usr/bin/env bash
# Creates .htaccess in the site root for Fasthosts / Apache shared hosting.
# Run from anywhere: ./deploy/create-htaccess.sh
# Or: bash deploy/create-htaccess.sh /path/to/volta.github.io

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SITE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT="${1:-${SITE_ROOT}/.htaccess}"

cat > "${OUT}" << 'EOF'
# SKEWRD — generated by deploy/create-htaccess.sh
# Stop browsers caching index.html so new ?v= JS/CSS URLs load after deploy.

<IfModule mod_headers.c>
  <FilesMatch "^index\.html$">
    Header set Cache-Control "no-cache, no-store, must-revalidate"
    Header set Pragma "no-cache"
    Header set Expires "0"
  </FilesMatch>
</IfModule>

# Optional: allow long cache for versioned static assets (?v= in URL makes each release unique).
<IfModule mod_headers.c>
  <FilesMatch "\.(css|js|json)$">
    Header set Cache-Control "public, max-age=604800"
  </FilesMatch>
</IfModule>
EOF

echo "Created: ${OUT}"
echo "Upload this file to your Fasthosts web root (same folder as index.html)."
